import { Dimensions, Platform, StyleSheet } from "react-native";

const { height: SH } = Dimensions.get("window");

export const styles = StyleSheet.create({
  root: { flex: 1, backgroundColor: "#09090B" },
  bgOrbTop: {
    position: "absolute",
    top: -120,
    right: -100,
    width: 320,
    height: 320,
    borderRadius: 160,
    backgroundColor: "#3B82F61E",
  },
  bgOrbBottom: {
    position: "absolute",
    bottom: -160,
    left: -120,
    width: 360,
    height: 360,
    borderRadius: 180,
    backgroundColor: "#8B5CF61E",
  },
  callHeader: {
    position: "absolute",
    top: Platform.OS === "ios" ? 54 : 28,
    left: 16,
    right: 16,
    zIndex: 25,
    gap: 12,
  },
  callHeaderHidden: {
    opacity: 0,
    transform: [{ translateY: -12 }],
  },
  callHeaderRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
  },
  callIdentity: {
    flex: 1,
    backgroundColor: "#FFFFFF14",
    borderWidth: 1,
    borderColor: "#FFFFFF24",
    borderRadius: 20,
    paddingHorizontal: 16,
    paddingVertical: 12,
    backdropFilter: "blur(8px)",
  },
  callKicker: {
    color: "#A5B4FC",
    fontSize: 10,
    fontWeight: "800",
    textTransform: "uppercase",
    letterSpacing: 1.2,
    marginBottom: 3,
  },
  callTitle: {
    color: "#FFFFFF",
    fontSize: 18,
    fontWeight: "800",
    letterSpacing: 0.2,
  },
  callSubtitle: {
    color: "#C7D2FE",
    fontSize: 12,
    marginTop: 2,
    opacity: 0.85,
  },
  statusPill: {
    backgroundColor: "#FFFFFF16",
    borderWidth: 1,
    borderColor: "#FFFFFF24",
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderRadius: 16,
  },
  statusPillText: {
    color: "#E2E8F0",
    fontSize: 12,
    fontWeight: "700",
  },
  livePill: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    backgroundColor: "#10B98122",
    borderWidth: 1,
    borderColor: "#34D39966",
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderRadius: 16,
  },
  liveDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: "#34D399",
  },
  livePillText: {
    color: "#D1FAE5",
    fontSize: 12,
    fontWeight: "800",
    fontFamily: Platform.OS === "ios" ? "Menlo" : "monospace",
  },
  headerActions: {
    flexDirection: "row",
    gap: 10,
  },
  headerChip: {
    flex: 1,
    backgroundColor: "#FFFFFF14",
    borderWidth: 1,
    borderColor: "#FFFFFF22",
    borderRadius: 16,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  headerChipActive: {
    backgroundColor: "#0F172A88",
    borderColor: "#7DD3FC66",
  },
  headerChipLabel: {
    color: "#94A3B8",
    fontSize: 10,
    fontWeight: "700",
    textTransform: "uppercase",
    letterSpacing: 1,
    marginBottom: 2,
  },
  headerChipValue: {
    color: "#F8FAFC",
    fontSize: 13,
    fontWeight: "800",
    letterSpacing: 0.4,
  },
  remoteContainer: { ...StyleSheet.absoluteFillObject },
  remoteVideo: { flex: 1, backgroundColor: "#09090B" },
  videoScrimTop: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    height: 180,
    backgroundColor: "#00000033",
  },
  videoScrimBottom: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 0,
    height: 220,
    backgroundColor: "#00000055",
  },
  remoteStateIndicators: {
    position: "absolute",
    top: 126,
    right: 16,
    gap: 8,
    zIndex: 15,
  },
  remoteBadge: {
    alignSelf: "flex-end",
    backgroundColor: "#0F172ACC",
    borderRadius: 999,
    borderWidth: 1,
    borderColor: "#FFFFFF22",
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  remoteBadgeText: {
    color: "#F8FAFC",
    fontSize: 12,
    fontWeight: "800",
  },
  stateIndicator: {
    backgroundColor: "#EF444422",
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderWidth: 1,
    borderColor: "#FCA5A544",
    alignSelf: "flex-end",
  },
  stateIndicatorText: {
    color: "#FCA5A5",
    fontSize: 12,
    fontWeight: "700",
    fontFamily: Platform.OS === "ios" ? "Menlo" : "monospace",
  },
  stateIndicatorSecondary: {
    backgroundColor: "#FFFFFF18",
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderWidth: 1,
    borderColor: "#FFFFFF22",
    alignSelf: "flex-end",
  },
  stateIndicatorSecondaryText: {
    color: "#E2E8F0",
    fontSize: 12,
    fontWeight: "700",
  },
  remoteVideoOffCard: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#09090B",
    gap: 10,
    paddingHorizontal: 24,
  },
  remoteBackdropGlow: {
    position: "absolute",
    width: 280,
    height: 280,
    borderRadius: 140,
    backgroundColor: "#5B5FED22",
    top: -30,
    right: -50,
  },
  remoteInitialsBadge: {
    width: 120,
    height: 120,
    borderRadius: 60,
    backgroundColor: "#0F172A",
    borderWidth: 1,
    borderColor: "#7DD3FC55",
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#000",
    shadowOpacity: 0.35,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 10 },
    elevation: 8,
  },
  remoteInitialsText: {
    color: "#E2E8F0",
    fontSize: 34,
    fontWeight: "800",
    letterSpacing: 1,
    fontFamily: Platform.OS === "ios" ? "Menlo" : "monospace",
  },
  remoteVideoOffTitle: {
    color: "#FFFFFF",
    fontSize: 22,
    fontWeight: "800",
  },
  remoteVideoOffSubtitle: {
    color: "#94A3B8",
    fontSize: 13,
  },
  remoteMetaRow: {
    flexDirection: "row",
    gap: 8,
    marginTop: 4,
  },
  remoteMetaChip: {
    backgroundColor: "#10B98122",
    borderRadius: 999,
    borderWidth: 1,
    borderColor: "#34D39955",
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  remoteMetaChipText: {
    color: "#D1FAE5",
    fontSize: 11,
    fontWeight: "700",
  },
  remoteMetaChipAlt: {
    backgroundColor: "#FFFFFF12",
    borderRadius: 999,
    borderWidth: 1,
    borderColor: "#FFFFFF20",
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  remoteMetaChipAltText: {
    color: "#E2E8F0",
    fontSize: 11,
    fontWeight: "700",
  },
  stateIndicatorRemoteCard: {
    marginTop: 8,
    backgroundColor: "#EF444422",
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderWidth: 1,
    borderColor: "#FCA5A544",
    alignItems: "center",
    justifyContent: "center",
  },
  waitingState: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#09090B",
  },
  waitingOverlay: {
    ...StyleSheet.absoluteFillObject,
    alignItems: "center",
    justifyContent: "center",
    gap: 16,
    paddingHorizontal: 24,
    backgroundColor: "rgba(0,0,0,0.5)",
  },
  waitingGlow: {
    position: "absolute",
    width: 320,
    height: 320,
    borderRadius: 160,
    backgroundColor: "#14B8A622",
    top: 70,
  },
  waitingAvatar: {
    width: 104,
    height: 104,
    borderRadius: 52,
    backgroundColor: "#0F172A",
    borderWidth: 1,
    borderColor: "#7DD3FC55",
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#000",
    shadowOpacity: 0.28,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 8 },
    elevation: 8,
  },
  waitingAvatarText: { fontSize: 40, color: "#E2E8F0" },
  waitingTitle: { color: "#FFFFFF", fontSize: 20, fontWeight: "800" },
  waitingSubtitle: {
    color: "#94A3B8",
    fontSize: 13,
    lineHeight: 19,
    textAlign: "center",
    maxWidth: 320,
  },
  roomCodeBtn: {
    backgroundColor: "#0F172A",
    borderWidth: 1,
    borderColor: "#7DD3FC33",
    borderRadius: 18,
    paddingHorizontal: 20,
    paddingVertical: 16,
    alignItems: "center",
    gap: 4,
    minWidth: 220,
  },
  roomCodeLabel: {
    fontSize: 10,
    color: "#94A3B8",
    fontWeight: "700",
    letterSpacing: 1.5,
    fontFamily: Platform.OS === "ios" ? "Menlo" : "monospace",
  },
  roomCodeValue: {
    fontSize: 24,
    fontWeight: "800",
    color: "#E2E8F0",
    letterSpacing: 4,
    fontFamily: Platform.OS === "ios" ? "Menlo" : "monospace",
  },
  roomCodeCopy: { fontSize: 11, color: "#7DD3FC", marginTop: 4, fontWeight: "700" },
  localPip: {
    position: "absolute",
    left: 16,
    top: 160,
    borderRadius: 18,
    overflow: "hidden",
    borderWidth: 2,
    borderColor: "#7DD3FC66",
    zIndex: 10,
    backgroundColor: "#0F172A",
    elevation: 12,
    shadowColor: "#000",
    shadowOpacity: 0.34,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 10 },
  },
  localVideo: { flex: 1 },
  pipLabel: {
    position: "absolute",
    top: 8,
    left: 8,
    zIndex: 2,
    backgroundColor: "#00000088",
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 4,
  },
  pipLabelText: {
    color: "#F8FAFC",
    fontSize: 9,
    fontWeight: "800",
    letterSpacing: 1,
    fontFamily: Platform.OS === "ios" ? "Menlo" : "monospace",
  },
  cameraOffCardCompact: {
    flex: 1,
    backgroundColor: "#0B1220",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    padding: 8,
  },
  initialsBadgeSmall: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: "#11131F",
    borderWidth: 1,
    borderColor: "#5B5FED66",
    alignItems: "center",
    justifyContent: "center",
  },
  initialsBadgeSmallText: {
    color: "#E8E8FF",
    fontSize: 14,
    fontWeight: "800",
    letterSpacing: 0.5,
    fontFamily: Platform.OS === "ios" ? "Menlo" : "monospace",
  },
  cameraOffCompactText: {
    color: "#E2E8F0",
    fontSize: 10,
    fontWeight: "700",
  },
  waitingPreviewCard: {
    width: "82%",
    maxWidth: 320,
    aspectRatio: 9 / 16,
    borderRadius: 22,
    overflow: "hidden",
    borderWidth: 1,
    borderColor: "#7DD3FC33",
    backgroundColor: "#07111C",
    marginTop: 6,
    shadowColor: "#000",
    shadowOpacity: 0.34,
    shadowRadius: 22,
    shadowOffset: { width: 0, height: 12 },
    elevation: 8,
  },
  waitingPreviewVideo: { flex: 1 },
  cameraOffCard: {
    flex: 1,
    backgroundColor: "#0B1220",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    padding: 14,
  },
  initialsBadgeLarge: {
    width: 88,
    height: 88,
    borderRadius: 44,
    backgroundColor: "#11131F",
    borderWidth: 1,
    borderColor: "#5B5FED66",
    alignItems: "center",
    justifyContent: "center",
  },
  initialsBadgeLargeText: {
    color: "#E8E8FF",
    fontSize: 30,
    fontWeight: "800",
    letterSpacing: 1,
    fontFamily: Platform.OS === "ios" ? "Menlo" : "monospace",
  },
  cameraOffTitle: {
    color: "#FFFFFF",
    fontSize: 15,
    fontWeight: "700",
  },
  cameraOffSubtitle: {
    color: "#94A3B8",
    fontSize: 12,
  },
  waitingPreviewLabel: {
    position: "absolute",
    left: 10,
    bottom: 10,
    backgroundColor: "#00000088",
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 4,
  },
  waitingPreviewLabelText: {
    color: "#E8E8FF",
    fontSize: 10,
    fontWeight: "700",
    letterSpacing: 0.6,
    fontFamily: Platform.OS === "ios" ? "Menlo" : "monospace",
  },
  mutedBadge: {
    position: "absolute",
    bottom: 6,
    left: 6,
    backgroundColor: "#EF444422",
    borderRadius: 999,
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderWidth: 1,
    borderColor: "#FCA5A544",
  },
  mutedBadgeText: {
    color: "#FCA5A5",
    fontSize: 8,
    fontWeight: "800",
    letterSpacing: 0.5,
    fontFamily: Platform.OS === "ios" ? "Menlo" : "monospace",
  },
  chatLauncher: {
    position: "absolute",
    right: 16,
    bottom: 92,
    zIndex: 24,
    backgroundColor: "#0F172AE6",
    borderWidth: 1,
    borderColor: "#7DD3FC55",
    borderRadius: 18,
    paddingHorizontal: 14,
    paddingVertical: 12,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    shadowColor: "#000",
    shadowOpacity: 0.3,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 8 },
    elevation: 10,
  },
  chatLauncherActive: {
    backgroundColor: "#111827F2",
    borderColor: "#A5B4FC66",
  },
  chatLauncherIcon: {
    color: "#FFFFFF",
    fontSize: 12,
    fontWeight: "800",
    textTransform: "uppercase",
    letterSpacing: 1,
  },
  chatLauncherText: {
    color: "#D7E5F2",
    fontSize: 11,
    fontWeight: "600",
  },
  chatSheet: {
    position: "absolute",
    left: 12,
    right: 12,
    bottom: 84,
    height: SH * 0.48,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    borderBottomLeftRadius: 20,
    borderBottomRightRadius: 20,
    backgroundColor: "#08111B",
    borderWidth: 1,
    borderColor: "#7DD3FC33",
    overflow: "hidden",
    zIndex: 30,
    shadowColor: "#000",
    shadowOpacity: 0.32,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 12 },
    elevation: 16,
  },
  chatSheetChrome: {
    paddingTop: 8,
    backgroundColor: "#08111B",
    borderBottomWidth: 1,
    borderBottomColor: "#163247",
  },
  chatSheetHandle: {
    alignSelf: "center",
    width: 42,
    height: 4,
    borderRadius: 999,
    backgroundColor: "#334155",
    marginBottom: 10,
  },
  chatSheetHeader: {
    paddingHorizontal: 16,
    paddingBottom: 12,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
  },
  chatSheetTitle: {
    color: "#FFFFFF",
    fontSize: 18,
    fontWeight: "800",
  },
  chatSheetSubtitle: {
    color: "#94A3B8",
    fontSize: 12,
    marginTop: 3,
  },
  chatSheetClose: {
    backgroundColor: "#FFFFFF10",
    borderWidth: 1,
    borderColor: "#FFFFFF18",
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  chatSheetCloseText: {
    color: "#E2E8F0",
    fontSize: 12,
    fontWeight: "700",
  },
  chatPanel: {
    position: "absolute",
    bottom: 110,
    left: 0,
    right: 0,
    height: SH * 0.45,
    zIndex: 30,
    borderTopWidth: 1,
    borderTopColor: "#1A1B2E",
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    overflow: "hidden",
  },
  chatInner: {
    backgroundColor: "#08111B",
  },
  controls: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    flexDirection: "column",
    justifyContent: "center",
    alignItems: "center",
    gap: 10,
    paddingBottom: Platform.OS === "ios" ? 46 : 30,
    paddingTop: 14,
    paddingHorizontal: 16,
    zIndex: 20,
  },
  controlsRowPrimary: {
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    gap: 10,
  },
  controlsRowSecondary: {
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    gap: 10,
  },
  controlsHidden: {
    opacity: 0,
    transform: [{ translateY: 18 }],
  },
  ctrlBtn: {
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#FFFFFF12",
    borderWidth: 1,
    borderColor: "#FFFFFF22",
    gap: 4,
  },
  ctrlBtnActive: { backgroundColor: "#7DD3FC22", borderColor: "#7DD3FC66" },
  ctrlBtnDanger: { backgroundColor: "#EF444422", borderColor: "#EF444466" },
  ctrlBtnDisabled: { opacity: 0.45, borderColor: "#FFFFFF18" },
  ctrlIcon: { color: "#FFFFFF" },
  ctrlIconDanger: {},
  ctrlIconDisabled: { color: "#CBD5E1" },
  ctrlLabel: { fontSize: 9, color: "#D7E5F2", marginTop: 2, fontWeight: "700" },
  endBtn: {
    width: 64,
    height: 64,
    borderRadius: 32,
    backgroundColor: "#EF4444",
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#EF4444",
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.5,
    shadowRadius: 12,
    elevation: 10,
  },
  endBtnIcon: {
    fontSize: 15,
    color: "#FFFFFF",
    fontWeight: "800",
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  pipSwapBadge: {
    position: "absolute",
    top: 8,
    right: 8,
    zIndex: 3,
    backgroundColor: "#0B132499",
    borderWidth: 1,
    borderColor: "#FFFFFF22",
    borderRadius: 999,
    paddingHorizontal: 8,
    paddingVertical: 4,
  },
  pipSwapBadgeText: {
    color: "#E2E8F0",
    fontSize: 10,
    fontWeight: "800",
    letterSpacing: 0.5,
  },
});
